### ISSUE TITLE
Cox regression with mimids object

### ISSUE THREAD

**Issue by janickweberpals** [FarhadPishgar/MatchThem#14]
Thanks so much for this fantastic and really helpful package!

In the documentation it is recommended that for Cox regression models,` coxph()` (survival package) should be used after weighting and `svycoxph()` (survey package) after matching when applying the `with()` function to a mimids object after imputation and matching to get accurate standard errors. It is also stated that for survey functions, no svydesign object is needed in `with()`. However, when I try to apply the `with()` function to a mimids object using `svycoxph()`, I receive the following error:

```
Error in .svycheck(design) : 
  argument "design" is missing, with no default
```

What would be the correct way to implement `svycoxph()` after multiple imputation and propensity score matching? I have created a [reproducible example](https://github.com/janickweberpals/svycoxphMI) that tries to compare effect estimates using `coxph` and `svycoxph()`. 

Example: https://github.com/janickweberpals/svycoxphMI

**Comment by ngreifer** [comment]
Hi Janick,

Call `svycoxph()` instead of `survey::svycoxph()` in the second argument of `with()`. This is because `MatchThem` checks to see if the first function called starts with "svy" to determine whether to use the survey infrastructure. Since you loaded the packages at the beginning of your script, you should not need to use `::` anywhere anyway.

@FarhadPishgar, perhaps this could be made to be more robust.

**Comment by janickweberpals** [comment]
Got it, thanks so much, this resolved my issue!
